server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:gopikrishhnaChokkalamani/spring-cloud-config-repo.git
          search-paths:
          - configuration/{application}/
          - configuration/
          private-key: |
                        --- Your Git Private Key, see github help to generate one---
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url.defaultZone: http://localhost:8700/eureka/

info:
  app:
    name: config-server
    description: Config Server
    version: v1.0
endpoints:
  actuator:
    enabled: true
    sensitive: true
  health:
    enabled: true
    sensitive: true
  metrics:
    enabled: true
    id: metrics
    sensitive: true
management:
  security:
    enabled: false